# Generated by Django 3.0 on 2020-12-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('user', models.CharField(max_length=50)),
                ('eday', models.IntegerField()),
                ('emonth', models.CharField(max_length=50)),
                ('etime', models.TimeField()),
                ('ename', models.CharField(max_length=50)),
                ('etext', models.TextField(max_length=250)),
                ('ecreationdate', models.DateTimeField(auto_now=True)),
                ('edate', models.DateField()),
                ('eweekday', models.CharField(max_length=50)),
            ],
        ),
    ]
